services:
  cvrunner:
    shm_size: "16gb"
    build:
      context: ..
      dockerfile: environments/Dockerfile
    image: cvrunner-local:latest
    working_dir: /workspace
    env_file:
      - ../.env
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

